numbers = [5, 2, 3, 7, 4, 5]
# numbers2 = numbers.copy()
# print(numbers.count(5))
# print(numbers.index(4))
# numbers.append(20)
# print(numbers)
# print(numbers2)
# numbers.insert(1, 6)
# print(numbers)
# numbers.remove(7)
# print(numbers)
# numbers.pop()
# print(numbers)
# numbers.reverse()
# print(numbers)
# numbers.sort()
# print(numbers)
# numbers.clear()
# print(numbers)
# numbers2.remove(5)
# print(numbers2)
# a = ['nihas', 'pandu', 'njknjnenj']
# a.sort()
# print(a)
numbers.remove(6)
print(numbers)